version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus/alerting-rules.yml:/etc/prometheus/alerting-rules.yml

  grafana:
    image: grafana/grafana-oss:10.1.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/ds/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  alert-manager:
    image: bitnami/alertmanager:latest
    container_name: alert-manager
    ports:
      - '9093:9093'
    volumes:
      - ./volumes/alert-manager/config.yml:/opt/bitnami/alertmanager/conf/config.yml

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025' # SMTP server port
      - '8025:8025' # HTTP server port

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    container_name: otel-collector
    volumes:
      - ./volumes/collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    restart: unless-stopped
    ports:
      - '1888:1888' # pprof extension
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver
      - '55679:55679' # zpages extension

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: unless-stopped
    ports:
      - '9411:9411'

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./volumes/tempo-config/tempo.yml:/etc/tempo.yml
    ports:
      - '3200:3200'   # tempo
      - '4317'  # otlp grpc

  loki:
    image: grafana/loki:latest
    container_name: loki
    command:
      - -config.file=/etc/loki/local-config.yaml
    ports:
      - '3100:3100'