groups:
  - name: service is down
    rules:
      - alert: 'service is down'
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service(s) are down