global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otlp-collector-spring-boot-observability'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          application: 'Spring Boot Observability'