global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'spring-boot-observability'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Spring Boot Observability'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alert-manager:9093']

rule_files:
  - alerting-rules.yml