spring:
  application:
    name: spring-boot-observability

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s