spring:
  application:
    name: spring-boot-observability

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, beans, mappings
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

  metrics:
    tags:
      department: ${SERVICE_DEPARTMENT:Software Development}
      team: ${SERVICE_TEAM:Observability}
      service: ${spring.application.name}
      env: ${SERVICE_ENVIRONMENT:dev}
      region: ${SERVICE_REGION:us-east1}
      instance.id: ${SERVICE_INSTANCE_ID:${random.uuid}}

  info:
    env:
      enabled: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

info:
  app:
    name: ${spring.application.name}
    description: This is a demo for spring boot 3 observability
    version: 1.0.0