receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: '0.0.0.0:8889'
    const_labels:
      label1: value1

  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, zipkin, otlp]
