receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  prometheus:
    endpoint: '0.0.0.0:8889'
    const_labels:
      label1: value1

  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
    format: proto

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ zipkin ]
